/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HiTech_View;

import HiTech_Controll.ProdutosControll;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexs
 */
public class CadastroProduto extends javax.swing.JInternalFrame {
    
    private String modoTela;
    private String categoria;
    
    
    
    public CadastroProduto() {
        initComponents();
        
        desabilitarFor();
        CarregarT();
    }
    
    public void LimparFor(){
        txtDescricao.setText("");
        txtMarca.setText("");
        txtQTD.setText("");
        txtCodigoBarras.setText("");
        txtValor.setText("");
        txtQTDadicional.setText("");
    }
    public void HabilitarFor(){
        //bgpGrupoCategoria.setSelected(, true);
        txtDescricao.setEditable(true);
        txtMarca.setEditable(true);
        txtCodigoBarras.setEditable(true);
        txtQTD.setEditable(true);
        txtValor.setEditable(true);
    }
    public void desabilitarFor(){
        //bgpGrupoCategoria.setSelected(bm, isIcon);
        txtDescricao.setEditable(false);
        txtMarca.setEditable(false);
        txtCodigoBarras.setEditable(false);
        txtQTD.setEditable(false);
        txtValor.setEditable(false);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpGrupoCategoria = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rdbCordas = new javax.swing.JRadioButton();
        rdbTeclas = new javax.swing.JRadioButton();
        rdbSopro = new javax.swing.JRadioButton();
        rdbPercussao = new javax.swing.JRadioButton();
        lblImagemProduto = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblQTD = new javax.swing.JLabel();
        txtQTD = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnEditQtdValor = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jpnProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblQTDadicional = new javax.swing.JLabel();
        txtQTDadicional = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        bgpGrupoCategoria.add(rdbCordas);
        rdbCordas.setText("Cordas");
        rdbCordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCordasActionPerformed(evt);
            }
        });

        bgpGrupoCategoria.add(rdbTeclas);
        rdbTeclas.setText("Teclas");
        rdbTeclas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTeclasActionPerformed(evt);
            }
        });

        bgpGrupoCategoria.add(rdbSopro);
        rdbSopro.setText("Sopro");
        rdbSopro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSoproActionPerformed(evt);
            }
        });

        bgpGrupoCategoria.add(rdbPercussao);
        rdbPercussao.setText("Percussão");
        rdbPercussao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPercussaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbCordas)
                .addGap(18, 18, 18)
                .addComponent(rdbTeclas)
                .addGap(18, 18, 18)
                .addComponent(rdbSopro)
                .addGap(18, 18, 18)
                .addComponent(rdbPercussao)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCordas)
                    .addComponent(rdbTeclas)
                    .addComponent(rdbSopro)
                    .addComponent(rdbPercussao)))
        );

        lblImagemProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDescricao.setText("Descrição:");

        txtDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMarca.setText("Marca:");

        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQTD.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblQTD.setText("Quantidade:");

        txtQTD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNovo.setText("Novo");
        btnNovo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditQtdValor.setText("Editar QTD e Valor");
        btnEditQtdValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEditQtdValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQtdValorActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Marca", "Quantidade", "valor"
            }
        ));
        jpnProdutos.setViewportView(tblProdutos);

        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblValor.setText("Valor:");

        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQTDadicional.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblQTDadicional.setText("QTD Adicional:");

        txtQTDadicional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar por Descrição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblCodigoBarras.setText("Codigo de barra:");

        txtCodigoBarras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditQtdValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescricao)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigoBarras)
                                            .addComponent(txtMarca))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblQTD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtQTD))))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jpnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQTDadicional, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQTDadicional, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                            .addComponent(lblQTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtQTD))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditQtdValor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQTDadicional, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQTDadicional, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbCordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCordasActionPerformed
        // TODO add your handling code here:
        categoria = "Cordas";
        this.lblImagemProduto.setIcon(new ImageIcon(getClass().getResource("/Imagens/corda.png")));
    }//GEN-LAST:event_rdbCordasActionPerformed

    private void rdbTeclasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTeclasActionPerformed
        // TODO add your handling code here:
        categoria = "Teclas";
        this.lblImagemProduto.setIcon(new ImageIcon(getClass().getResource("/Imagens/tecla.png")));
    }//GEN-LAST:event_rdbTeclasActionPerformed

    private void rdbSoproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSoproActionPerformed
        // TODO add your handling code here:
        categoria = "Sopro";
        this.lblImagemProduto.setIcon(new ImageIcon(getClass().getResource("/Imagens/sopro.png")));
    }//GEN-LAST:event_rdbSoproActionPerformed

    private void rdbPercussaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPercussaoActionPerformed
        // TODO add your handling code here:
        categoria = "Percussão";
        this.lblImagemProduto.setIcon(new ImageIcon(getClass().getResource("/Imagens/percussao.png")));
    }//GEN-LAST:event_rdbPercussaoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        modoTela = "Criar";

        LimparFor();
        HabilitarFor();
        
    }//GEN-LAST:event_btnNovoActionPerformed
    
    private void btnEditQtdValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQtdValorActionPerformed
        // TODO add your handling code here:
        
        if(tblProdutos.getRowCount() > 0 ){
            
            if(tblProdutos.getSelectedRow() >= 0 ){
                HabilitarFor();
                modoTela = "Editar";
                
                
                txtCodigoBarras.setText(tblProdutos.getModel().getValueAt(tblProdutos.getSelectedRow(),1).toString());
                txtMarca.setText(tblProdutos.getModel().getValueAt(tblProdutos.getSelectedRow(), 2).toString());
                txtQTD.setText(tblProdutos.getModel().getValueAt(tblProdutos.getSelectedRow(),3).toString());
                txtDescricao.setText(tblProdutos.getModel().getValueAt(tblProdutos.getSelectedRow(),4).toString());
                txtValor.setText(tblProdutos.getModel().getValueAt(tblProdutos.getSelectedRow(),5).toString());
            
            }else{
                JOptionPane.showMessageDialog(null, "Clique para editar!");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum produto para editar!");
        }
        
    }//GEN-LAST:event_btnEditQtdValorActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if(tblProdutos.getRowCount() > 0){
            int num_linhas = tblProdutos.getSelectedRow();
            if(num_linhas < 0){
                JOptionPane.showMessageDialog(null, "Selecione o Produto!");
                return;
            }
            
            String excluir = tblProdutos.getModel().getValueAt(num_linhas, 1).toString();
            if(ProdutosControll.excluir(excluir)){
                this.CarregarT();
                JOptionPane.showMessageDialog(null, "Produto excluido!");
            }else{
               JOptionPane.showMessageDialog(null, "Erro ao excluir!");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum produto Cadastrado!");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
//        String categori = "";
//        categori = bgpGrupoCategoria.getSelection().getActionCommand();
        if(validarFor()){
            if(modoTela.equals("Criar")){
                if(ProdutosControll.salvar(categoria, txtCodigoBarras.getText(), 
                                          txtDescricao.getText(), txtMarca.getText(), txtQTD.getText(), txtValor.getText())){
                    
                    CarregarT();
                    JOptionPane.showMessageDialog(null, "Produto cadastrado!");
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar");
                }
                
            }else{
                if(ProdutosControll.atualizar(bgpGrupoCategoria.getSelection().getActionCommand(), txtCodigoBarras.getText(), 
                                          txtDescricao.getText(), txtMarca.getText(), txtQTD.getText(), txtValor.getText())){
                    
                    CarregarT();
                    JOptionPane.showMessageDialog(null, "Produto atualizado!");
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar");
                }
            }
            LimparFor();
            desabilitarFor();
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    
    public void CarregarT(){
        
        ArrayList<String[]> linhasProd = ProdutosControll.getProdutos();
        
        DefaultTableModel tmProdutos = new DefaultTableModel();
        
        tmProdutos.addColumn("Categoria");
        tmProdutos.addColumn("Cod Barras");
        tmProdutos.addColumn("Descrição");
        tmProdutos.addColumn("Marca");
        tmProdutos.addColumn("QTD");
        tmProdutos.addColumn("Valor");
        tblProdutos.setModel(tmProdutos);
        
        for(String[] P:linhasProd){
            tmProdutos.addRow(P);
        }
        
        
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpGrupoCategoria;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditQtdValor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jpnProdutos;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblImagemProduto;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblQTD;
    private javax.swing.JLabel lblQTDadicional;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rdbCordas;
    private javax.swing.JRadioButton rdbPercussao;
    private javax.swing.JRadioButton rdbSopro;
    private javax.swing.JRadioButton rdbTeclas;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtQTD;
    private javax.swing.JTextField txtQTDadicional;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    
    public boolean validarFor(){
    
     if(this.bgpGrupoCategoria.getButtonCount() == 0){
         JOptionPane.showMessageDialog(null, "Categoria não selecionada!");
         return false;
      }
     if(this.txtDescricao.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Campo descrição incompleto! ");
         return false;
     }
     if(this.txtMarca.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Campo marca incompleto! ");
         return false;
     }
     if(this.txtQTD.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Campo quantidade incompleto! ");
         return false;
     }
     if(this.txtCodigoBarras.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Campo codigo de barras incompleto! ");
         return false;
     }
     if(this.txtValor.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Campo valor incompleto! ");
         return false;
     }
     
         
      return true;   
     }

}
